import React from "react";

/* Styles */
import styles from "./styles.module.css";

function Statistics() {
  return (
    <section id="statistics" className={styles.Statistics}>
      <span className={styles.Decoration} />

      <div className={styles.Container}>
        <h2 className={styles.Heading}>
          Better machine performance for better maintenance teams&apos;
          productivity
        </h2>

        <div className={styles.ContentWrapper}>
          <div className={styles.Statistic}>
            <h5 className={styles.Title}>90%</h5>
            <p className={styles.Subtitle}>
              Assertiveness of Insights generated by Tractian platform
            </p>
          </div>
          <div className={styles.Statistic}>
            <h5 className={styles.Title}>45%</h5>
            <p className={styles.Subtitle}>
              Increased reliability of machines with Tractian Solution
            </p>
          </div>
          <div className={styles.Statistic}>
            <h5 className={styles.Title}>30%</h5>
            <p className={styles.Subtitle}>
              Reduction of last-minute maintenance occurrences
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default Statistics;
